#+TITLE: CV
#+AUTHOR: Parth Trivedi
#+DRAFT: false
#+LAYOUT: single

Welcome to my CV or Resume!!

* Education
** Auckland University of Technology
FEBRUARY 2023 – NOVEMBER 2025

Studying Bachelor in Computer and Information Sciences, majoring in Software Development and Cyber Security.

* Experience
** Wordpress/Shopify Developer (Casual)
JANUARY 2020 - PRESENT

Building and designing the business website and maintaining the Shopify store.

** Automation Engineer (Contract)
JULY 2022 - JANUARY 2024

Developing custom software solutions to automate large amounts of data entry and data validating processes.

** Junior Software Developer / SysAdmin
DECEMBER 2023 – JULY 2024

Providing support for a variety of company products including servers, networking, and applications. Worked on assigned internal projects, such as application server setup

* Skills
- Quick learning
- Problem Solving
- Communication
- Working in teams
- Motivated

* Qualifications
- Microsoft Technology Associate in Javascript & Python
- Cisco CCNAv7: Introduction to Networks, Switching and Routing

* Technologies
- Python - Proficient
- Go - Proficient
- Java - Proficient
- Javascript/NodeJS - Proficient
- Wordpress - Proficient
- Linux - Proficient

* Projects
** Library Management System Automation
Automates creation, updating, and archiving of numerous records in a remote library management system.

Uses various data checking processes and API endpoints. Written in Python.

** Student Management System Automation 
Exports relevant student data after determining student status based on enrollment.

Creates/updates student information in remote student management system using a REST API. Written in Go.

** SafeZone – Velocity 100K Challenge at University of Auckland
Early warning, collision detection system for pedestrian safety. Includes a mobile app and a real-time server-based collision detection system.

Used React Native, Websockets, BunJS.
